import os
import stat
from pathlib import Path

def setup_hooks():
    git_dir = Path(".git")
    if not git_dir.exists():
        print("❌ Error: .git directory not found. Are you in the project root?")
        return

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    hook_content = """#!/bin/bash
# Auto-generated by setup_hooks.py
uv run python scripts/verify_dev.py
"""

    for hook_name in ["pre-commit", "pre-push"]:
        hook_path = hooks_dir / hook_name
        with open(hook_path, "w") as f:
            f.write(hook_content)
        
        # Make executable
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        print(f"✅ Installed {hook_name} hook")

if __name__ == "__main__":
    setup_hooks()
